# Generated by Django 4.2.6 on 2023-11-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_ID', models.IntegerField()),
                ('make_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('vehicle', models.ManyToManyField(to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
