# Generated by Django 4.2.6 on 2023-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate',
            field=models.ManyToManyField(to='vehicle.rate'),
        ),
    ]
