# Generated by Django 4.2.6 on 2023-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_rate_vehicle_vehicle_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='vehicle',
            field=models.ManyToManyField(to='vehicle.vehicle'),
        ),
    ]
